import NodeDataMapping from "./NodeDataMapping"
export default Object.assign({
  'allow-features': ['camera', 'allow-features'],
  'background': ['camera', 'background'],
  'clear-color': ['camera', 'clear-color'],
  'clear-depth': ['camera', 'clear-depth'],
  'clear-stencil': ['camera', 'clear-stencil'],
  'cull-mask': ['camera', 'cull-mask'],
  'depth': ['camera', 'depth'],
  'far': ['camera', 'far'],
  'fov': ['camera', 'fov'],
  'is-ar-camera': ['camera', 'is-ar-camera'],
  'is-clear-color': ['camera', 'is-clear-color'],
  'is-clear-depth': ['camera', 'is-clear-depth'],
  'is-clear-stencil': ['camera', 'is-clear-stencil'],
  'is-perspective': ['camera', 'is-perspective'],
  'near': ['camera', 'near'],
  'orth-size': ['camera', 'orth-size'],
  'post-process': ['camera', 'post-process'],
  'render-target': ['camera', 'render-target'],
  'target': ['camera', 'target'],
},NodeDataMapping)